<?php
/**
 * @package     Mondrian
 * @subpackage  Component File
 *
 * @copyright   Copyright (C) 2005 - 2013 Joomlashack. Meritage Assets.  All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

$lang = JFactory::getLanguage();
$tag = $lang->getTag();
$dir = ($lang->isRTL() ? "rtl" : "ltr");

?>
<!DOCTYPE html>
<html lang="<?php echo $tag ?>" dir="<?php echo $dir ?>">
<head>
<jdoc:include type="head" />
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/wright/css/template.css.php" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseurl ?>/templates/<?php echo $this->template ?>/wright/css/template-responsive.css.php" type="text/css" />
</head>
<body class="contentpane">
	<jdoc:include type="message" />
	<jdoc:include type="component" />
</body>
</html>
