<?php
/**
 * @copyright   Copyright (C) 2005 - 2012 Joomlashack / Meritage Assets
 * @author      Joomlashack
 * @package     Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');
$footerWrapp =" container";
// get the bootstrap row mode ( row / row-fluid )
$gridMode = $this->params->get('bs_rowmode','row-fluid');
$containerClass = 'container';
if ($gridMode == 'row-fluid') {
    $containerClass = 'container-fluid';
}else{
    $fixedClass = ' fixed';
}

$bodyclass = "";
if ($this->countModules('toolbar')) {
    $bodyclass = "toolbarpadding";
}
$responsivePage = $this->params->get('responsive','1');
$responsive = ' responsive';
if ($responsivePage == 0) {
    $responsive = ' no-responsive';
}
$mondrianFtBlog = $this->params->get('mondrian_featured_blog','1');
if ($mondrianFtBlog) {
    $mondrianFtBlogClass = ' mondrianFtBlog';
}
// sidebarClass

$sidebarClass= ' no-sidebar';
if ($this->countModules('sidebar1') && $this->countModules('sidebar2')){
    $sidebarClass= ' sb1 sb2';
}elseif ($this->countModules('sidebar2')) {
        $sidebarClass = ' sb2';
}elseif ($this->countModules('sidebar1')) {
        $sidebarClass = ' sb1';
}

$mondrianLogoAbsolute = ($this->params->get('mondrian_logo_on_featured','0') == '1' ? true : false);
$mondrianGridTopBackground = $this->params->get('mondrian_grid_top_background_color','color_four');
$mondrianGridTo2pBackground = $this->params->get('mondrian_grid_top2_background_color','color_four');
$mondrianGridTop3Background = $this->params->get('mondrian_grid_top3_background_color','color_four');

$mainContainer="container";
$mainGridMode="row";
$parentContainer="container-fluid";
$parentGridMode="row-fluid";
if ($containerClass =="container-fluid")  {
    $mainContainer="container-fluid";
    $mainGridMode="row-fluid";
}elseif($sidebarClass ==' no-sidebar'){
    $mainContainer="container-mondrian";
    $mainGridMode="row-mondrian";
    $parentContainer="";
    $parentGridMode="";
}

switch ($mondrianGridTopBackground) {
    case 'color_one':
        $gridTopBackground = " color_one";
        break;
    case 'color_two':
        $gridTopBackground = " color_two";
        break;
    case 'color_three':
        $gridTopBackground = " color_three";
        break;
    case 'color_four':
        $gridTopBackground = " color_four";
        break;
    case 'color_five':
        $gridTopBackground = " color_five";
        break;
    case 'color_six':
        $gridTopBackground = " color_six";
        break;

}
switch ($mondrianGridTo2pBackground) {
    case 'color_one':
        $gridTop2Background = " color_one";
        break;
    case 'color_two':
        $gridTop2Background = " color_two";
        break;
    case 'color_three':
        $gridTop2Background = " color_three";
        break;
    case 'color_four':
        $gridTop2Background = " color_four";
        break;
    case 'color_five':
        $gridTop2Background = " color_five";
        break;
    case 'color_six':
        $gridTop2Background = " color_six";
        break;

}
switch ($mondrianGridTop3Background) {
    case 'color_one':
        $gridTop3Background = " color_one";
        break;
    case 'color_two':
        $gridTop3Background = " color_two";
        break;
    case 'color_three':
        $gridTop3Background = " color_three";
        break;
    case 'color_four':
        $gridTop3Background = " color_four";
        break;
    case 'color_five':
        $gridTop3Background = " color_five";
        break;
    case 'color_six':
        $gridTop3Background = " color_six";
        break;

}

?>
<doctype>
<html>
<head>
    
<w:head />
</head>
<body class="<?php if ($bodyclass != "") { echo $bodyclass . $responsive;  } ?> <?php echo $mondrianFtBlogClass . $sidebarClass . $fixedClass; ?>">
    <?php if ($this->countModules('toolbar')) : ?>
        <!-- toolbar -->
        <div class="wrappToolbar">
            <w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode;?>" wrapClass="navbar-fixed-top" type="toolbar" name="toolbar" />
        </div>
        <div class="<?php echo $containerClass ?> wrapp-btnToolbar" style="height: 0;">
            <div id="btnToolbar" class="hidden-tablet hidden-phone"></div>
        </div>
    <?php endif; ?>
    <div class="<?php echo $parentContainer; ?>">
        <div class="<?php echo $parentGridMode; ?>">
            <div class="mondrian-container">
                <!-- header -->
                    <header id="header" class="<?php if ($mondrianLogoAbsolute): ?>header-absolute<?php endif; ?>">
                        <div class="<?php echo $containerClass ?>">
                            <div class="<?php echo $gridMode; ?> clearfix wrapp-logo">
                                <w:logo name="top" type="xhtml"/>
                            </div>
                        </div>
                    </header>
                
                <!-- featured -->
                <?php if ($this->countModules('featured')) : ?>
                    <div id="featured">
                        <w:module type="none" name="featured" chrome="xhtml" />
                    </div>
                <?php endif; ?>
                <!-- grid-top -->
                <?php if ($this->countModules('grid-top')) : ?>
                    <div id="grid-top" class="<?php echo $gridTopBackground; ?>">
                        <div class="<?php echo $containerClass; ?>">
                            <w:module type="row-fluid" name="grid-top" chrome="wrightflexgrid" />
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-top2')) : ?>
                <!-- grid-top2 -->
                    <div id="grid-top2" class="<?php echo $gridTo2pBackground; ?>">
                        <div class="<?php echo $containerClass; ?>">
                            <w:module type="row-fluid" name="grid-top2" chrome="wrightflexgrid" />
                        </div>
                    </div>
                <?php endif; ?>
                <div class="<?php echo $mainContainer;?> main-wrapp">
                    <div id="main-content" class="<?php echo $mainGridMode; ?>">
                        <!-- sidebar1 -->
                        <aside id="sidebar1">
                            <w:module name="sidebar1" chrome="xhtml" />
                        </aside>
                        <!-- main -->
                        <section id="main">
                            <?php if ($this->countModules('above-content')) : ?>
                            <!-- above-content -->
                                <div id="above-content">
                                    <div class="<?php echo $containerClass; ?>">
                                        <div class="<?php echo $gridMode; ?>">
                                            <div class="span12">
                                                <w:module type="none" name="above-content" chrome="xhtml" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <?php if ($this->countModules('breadcrumbs')) : ?>
                                <!-- breadcrumbs -->
                                <div id="breadcrumbs">
                                        <div class="<?php echo $containerClass; ?>">
                                            <div class="<?php echo $gridMode; ?>">
                                                <div class="span12">
                                                    <w:module type="single" name="breadcrumbs" chrome="none" />
                                                </div>
                                            </div>
                                        </div>
                                </div>
                            <?php endif; ?>
                            <!-- component -->
                            <w:content />
                            <?php if ($this->countModules('below-content')) : ?>
                            <!-- below-content -->
                                <div id="below-content">
                                    <div class="<?php echo $containerClass; ?>">
                                        <div class="<?php echo $gridMode; ?>">
                                            <div class="span12">
                                                <w:module type="none" name="below-content" chrome="xhtml" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </section>
                        <!-- sidebar2 -->
                        <aside id="sidebar2">
                            <w:module name="sidebar2" chrome="xhtml" />
                        </aside>
                    </div>
                </div>
                <?php if ($this->countModules('grid-bottom')) : ?>
                <!-- grid-bottom -->
                <div id="grid-bottom" class="<?php echo $gridTop3Background; ?>">
                    <div class="<?php echo $containerClass; ?>">
                        <w:module type="row-fluid" name="grid-bottom" chrome="wrightflexgrid" />
                    </div>
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-bottom2')) : ?>
                    <!-- grid-bottom2 -->
                    <div id="grid-bottom2" >
                        <div class="<?php echo $containerClass; ?>">
                            <div class="bd-grid-bottom2"></div>
                            <div class="grid-bottom2-inner">
                                <w:module type="row-fluid" name="grid-bottom2" chrome="wrightflexgrid" />
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if ($this->countModules('bottom-menu')) : ?>
                <!-- bottom-menu -->
                        <w:nav containerClass="container-fluid" rowClass="<?php echo $gridMode;?>" name="bottom-menu" />
                <?php endif; ?>
            </div>
        </div>
    </div>
    
    <!-- footer -->
    <div class="wrapper-footer">
        <footer id="footer" class="<?php if ($this->params->get('stickyFooter',1)) : ?> sticky<?php endif;?>">
             <div class="<?php echo $containerClass; ?> footer-inner">
                 <div class="container-fluid">
                     <?php if ($this->countModules('footer')) : ?>
                         <w:module type="row-fluid" name="footer" chrome="wrightflexgrid" />
                      <?php endif; ?>
                     <w:footer />
                 </div>
             </div>
        </footer>
    </div>
    <script type='text/javascript' src='<?php echo JURI::root(true) ?>/templates/js_mondrian/js/mondrian.js'></script>
</body>
</html>
