<?php
/**
 * @copyright   Copyright (C) 2005 - 2012 Joomlashack / Meritage Assets
 * @author      Joomlashack
 * @package     Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');
$footerWrapp =" container";
// get the bootstrap row mode ( row / row-fluid )
$gridMode = $this->params->get('bs_rowmode','row-fluid');
$containerClass = 'container';
if ($gridMode == 'row-fluid') {
    $containerClass = 'container-fluid';
    $footerWrapp =" container-fluid";
}

$bodyclass = "";
if ($this->countModules('toolbar')) {
    $bodyclass = "toolbarpadding";
}
$responsivePage = $this->params->get('responsive','1');
$responsive = ' responsive';
if ($responsivePage == 0) {
    $responsive = ' no-responsive';
}
$mondrianFtBlog = $this->params->get('mondrian_featured_blog','1');
if ($mondrianFtBlog) {
    $mondrianFtBlogClass = ' mondrianFtBlog';
}
if ($this->countModules('sidebar1') && $this->countModules('sidebar2')){
    $sidebarClass= ' sb1 sb2';
}elseif ($this->countModules('sidebar2')) {
        $sidebarClass = ' sb2';
}elseif ($this->countModules('sidebar1')) {
        $sidebarClass = ' sb1';
}
$mondrianLogoAbsolute = ($this->params->get('mondrian_logo_on_featured','0') == '1' ? true : false);

?>
<doctype>
<html>
<head>
    
<w:head />
</head>
<body class="<?php if ($bodyclass != "") { echo $bodyclass . $responsive;  } ?> <?php echo $mondrianFtBlogClass . $sidebarClass; ?>">
    <div class="BgAlternate"></div>
    <?php if ($this->countModules('toolbar')) : ?>
        <!-- toolbar -->
        <div class="wrappToolbar">
            <w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode;?>" wrapClass="navbar-fixed-top" type="toolbar" name="toolbar" />
        </div>
        <div class="<?php echo $containerClass ?> wrapp-btnToolbar" style="height: 0;">
            <div id="btnToolbar" class="hidden-tablet hidden-phone"></div>
        </div>
    <?php endif; ?>
    <div class="<?php echo $containerClass ?> mondrian-container">
<div class="container-fluid">
    <!-- header -->
    <header id="header"  <?php if ($mondrianLogoAbsolute): ?>class="header-absolute"<?php endif; ?>>
        <div class="row-fluid clearfix wrapp-logo">
            <w:logo name="top" type="xhtml"/>
        </div>
    </header>
    
    <!-- featured -->
    <?php if ($this->countModules('featured')) : ?>
    <div id="featured">
        <w:module type="none" name="featured" chrome="xhtml" />
    </div>
    <?php endif; ?>
    <!-- grid-top -->
    <?php if ($this->countModules('grid-top')) : ?>
    <div id="grid-top">
        <w:module type="row-fluid" name="grid-top" chrome="wrightflexgrid" />
    </div>
    <?php endif; ?>
    <?php if ($this->countModules('grid-top2')) : ?>
    <!-- grid-top2 -->
    <div id="grid-top2">
        <w:module type="row-fluid" name="grid-top2" chrome="wrightflexgrid" />
    </div>
    <?php endif; ?>
    <div id="main-content" class="row-fluid">
        <!-- sidebar1 -->
        <aside id="sidebar1">
            <w:module name="sidebar1" chrome="xhtml" />
        </aside>
        <!-- main -->
        <section id="main">
            <?php if ($this->countModules('above-content')) : ?>
            <!-- above-content -->
            <div id="above-content">
                <w:module type="none" name="above-content" chrome="xhtml" />
            </div>
            <?php endif; ?>
            <?php if ($this->countModules('breadcrumbs')) : ?>
            <!-- breadcrumbs -->
            <div id="breadcrumbs">
                    <w:module type="single" name="breadcrumbs" chrome="none" />
            </div>
            <?php endif; ?>
            <!-- component -->
            <w:content />
            <?php if ($this->countModules('below-content')) : ?>
            <!-- below-content -->
            <div id="below-content">
                <w:module type="none" name="below-content" chrome="xhtml" />
            </div>
            <?php endif; ?>
        </section>
        <!-- sidebar2 -->
        <aside id="sidebar2">
            <w:module name="sidebar2" chrome="xhtml" />
        </aside>
    </div>
    <?php if ($this->countModules('grid-bottom')) : ?>
    <!-- grid-bottom -->
    <div id="grid-bottom" >
                    <w:module type="row-fluid" name="grid-bottom" chrome="wrightflexgrid" />
    </div>
    <?php endif; ?>
    <?php if ($this->countModules('grid-bottom2')) : ?>
        <!-- grid-bottom2 -->
        <div id="grid-bottom2" >
            <div class="bd-grid-bottom2"></div>
            <w:module type="row-fluid" name="grid-bottom2" chrome="wrightflexgrid" />
        </div>
    <?php endif; ?>
    <?php if ($this->countModules('bottom-menu')) : ?>
    <!-- bottom-menu -->
            <w:nav containerClass="container-fluid" rowClass="<?php echo $gridMode;?>" name="bottom-menu" />
    <?php endif; ?></div>
        
    </div>
    
    <!-- footer -->
    <div class="wrapper-footer<?php echo $footerWrapp; ?>">
        <footer id="footer" class="<?php if ($this->params->get('stickyFooter',1)) : ?> sticky<?php endif;?>">
             <div class="<?php echo $containerClass; ?>">
                 <div class="container-fluid">
                     <?php if ($this->countModules('footer')) : ?>
                         <w:module type="row-fluid" name="footer" chrome="wrightflexgrid" />
                      <?php endif; ?>
                     <w:footer />
                 </div>
             </div>
        </footer>
    </div>
    <script type='text/javascript' src='<?php echo JURI::root(true) ?>/templates/js_mondrian/js/mondrian.js'></script>
</body>
</html>
